platform :ios, '10.0'

use_frameworks!

target 'RoxchatClientLibrary_Example' do
    
    pod 'RoxchatClientLibrary', :path => '../'
    pod 'RoxChatMobileWidget', :path => '../../mobile-widget-ios'
    
    pod 'Cosmos', '~> 19.0.3', :inhibit_warnings => true
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    pod 'SlackTextViewController', :inhibit_warnings => true
    pod 'SnapKit', :inhibit_warnings => true
    pod 'SQLite.swift', '0.13.3', :inhibit_warnings => true # RoxchatClientLibrary dependency – added to inhibit its warnings.
    pod 'Nuke', '~> 8.0', :inhibit_warnings => true
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'RoxchatClientLibrary' || target.name == 'SQLite.swift' || target.name == 'Cosmos' || target.name == 'Nuke'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '5.0'
                end
            else
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.2'
                end
            end

            if target.name == 'Nuke' || target.name == 'Cosmos' || target.name == 'Crashlytics' || target.name == 'Fabric' || target.name == 'SlackTextViewController'
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
                end
            end

            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
                    config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
                end
            end
        end
    end
    
end
